from LinkedList.Singly.SinglyLinkedList import SinglyLinkedList

singly_linkedlist = SinglyLinkedList()
singly_linkedlist.display()
singly_linkedlist.delete_head()
singly_linkedlist.search(9)
singly_linkedlist.insert(6)
singly_linkedlist.insert(5)
singly_linkedlist.insert(7)
singly_linkedlist.display()
singly_linkedlist.delete_head()
singly_linkedlist.display()
singly_linkedlist.search(7)
singly_linkedlist.search(9)
singly_linkedlist.insert(5)
singly_linkedlist.insert(13)
singly_linkedlist.insert(4)
singly_linkedlist.display()
singly_linkedlist.delete_tail()
singly_linkedlist.display()
singly_linkedlist.delete_at(2)
singly_linkedlist.display()
singly_linkedlist.delete_at(2)
singly_linkedlist.display()